from __future__ import annotations

ROUTE_GROUPS: list[dict[str, object]] = [
    {
        "domain": "health",
        "nodeModule": "apps/daemon/src/server.ts",
        "pythonStatus": "implemented",
        "routes": ["GET /health", "GET /api/backend/architecture", "GET /api/python-daemon/routes"],
    },
    {
        "domain": "auth-tenants",
        "nodeModule": "apps/daemon/src/routes/auth-routes.ts",
        "pythonStatus": "implemented",
        "routes": [
            "POST /api/auth/login",
            "POST /api/auth/create-account",
            "GET /api/auth/session",
            "POST /api/auth/logout",
            "POST /api/tenants",
            "POST /api/auth/switch-tenant",
            "GET /api/tenant-members",
            "POST /api/tenant-members",
            "PATCH /api/tenant-members/:accountId",
            "DELETE /api/tenant-members/:accountId",
        ],
    },
    {
        "domain": "billing",
        "nodeModule": "apps/daemon/src/routes/billing-routes.ts",
        "pythonStatus": "implemented",
        "routes": ["GET /api/billing/plans", "GET /api/billing/tenant", "PATCH /api/billing/tenant/plan"],
    },
    {
        "domain": "agent-execution",
        "nodeModule": "apps/daemon/src/routes/agent-routes.ts",
        "pythonStatus": "partial-readonly",
        "routes": [
            "GET /api/providers",
            "POST /api/providers/:providerId/check",
            "GET /api/agent-tasks",
            "GET /api/agent-tasks/:taskId",
            "GET /api/agent-tasks/:taskId/events",
            "GET /api/agent-tasks/:taskId/turns",
            "GET /api/approvals",
            "GET /api/workflow-runs",
            "GET /api/workflow-runs/:runId",
            "POST /api/agent-tasks",
            "GET /api/agent-tasks/:taskId/events/stream",
            "POST /api/approvals/:approvalId/decision",
        ],
    },
    {
        "domain": "workspace-data",
        "nodeModule": "apps/daemon/src/routes/*-routes.ts",
        "pythonStatus": "partial-readonly",
        "routes": [
            "GET /api/workspace-file",
            "GET /api/profile-overview",
            "GET /api/resumes",
            "GET /api/resume",
            "GET /api/resumes/diagnostics",
            "POST /api/resumes/save-generated",
            "POST /api/resumes/save",
            "GET /api/applications",
            "POST /api/application-events",
            "POST /api/application-events/update",
            "POST /api/application-events/delete",
            "GET /api/reports",
            "GET /api/report",
            "GET /api/experience-overview",
            "POST /api/experience-metadata",
            "GET /api/recruitment-market",
            "POST /api/recruitment-market/import",
            "POST /api/recruitment-market/manual-jobs",
            "DELETE /api/recruitment-market/:id",
            "GET /api/evidence-requests",
            "POST /api/evidence-requests/fulfill",
            "POST /api/evidence-notes",
        ],
    },
]
