from __future__ import annotations

ROUTE_GROUPS: list[dict[str, object]] = [
    {
        "domain": "health",
        "nodeModule": "apps/daemon/src/server.ts",
        "pythonStatus": "implemented",
        "routes": ["GET /health", "GET /api/backend/architecture", "GET /api/python-daemon/routes"],
    },
    {
        "domain": "auth-tenants",
        "nodeModule": "apps/daemon/src/routes/auth-routes.ts",
        "pythonStatus": "implemented",
        "routes": [
            "POST /api/auth/login",
            "POST /api/auth/create-account",
            "GET /api/auth/session",
            "POST /api/auth/logout",
            "POST /api/tenants",
            "POST /api/auth/switch-tenant",
            "GET /api/tenant-members",
            "POST /api/tenant-members",
            "PATCH /api/tenant-members/:accountId",
            "DELETE /api/tenant-members/:accountId",
        ],
    },
    {
        "domain": "billing",
        "nodeModule": "apps/daemon/src/routes/billing-routes.ts",
        "pythonStatus": "implemented",
        "routes": ["GET /api/billing/plans", "GET /api/billing/tenant", "PATCH /api/billing/tenant/plan"],
    },
    {
        "domain": "sync",
        "nodeModule": "apps/daemon/src/routes/sync-routes.ts",
        "pythonStatus": "implemented",
        "routes": ["GET /api/sync/outbox", "POST /api/sync/mark-pushed", "POST /api/sync/push-to-cloud"],
    },
    {
        "domain": "connectors",
        "nodeModule": "apps/daemon/src/routes/connector-routes.ts",
        "pythonStatus": "implemented",
        "routes": [
            "GET /api/connectors",
            "GET /api/connectors/:connectorId",
            "POST /api/connectors/qq-email/test",
            "GET /api/connectors/qq-email/credential",
            "POST /api/connectors/qq-email/credential",
            "POST /api/connectors/qq-email/messages",
            "POST /api/connectors/qq-email/attachments",
        ],
    },
    {
        "domain": "agent-execution",
        "nodeModule": "apps/daemon/src/routes/agent-routes.ts",
        "pythonStatus": "partial-lifecycle",
        "routes": [
            "GET /api/providers",
            "POST /api/providers/:providerId/check",
            "POST /api/agent-attachments",
            "GET /api/agent-tasks",
            "POST /api/agent-tasks",
            "POST /api/local-commands",
            "GET /api/agent-execution-queue",
            "GET /api/agent-tasks/:taskId",
            "DELETE /api/agent-tasks/:taskId",
            "POST /api/agent-tasks/:taskId/cancel",
            "GET /api/agent-tasks/:taskId/events",
            "GET /api/agent-tasks/:taskId/turns",
            "GET /api/approvals",
            "GET /api/workflow-runs",
            "GET /api/workflow-runs/:runId",
            "GET /api/agent-tasks/:taskId/events/stream",
            "POST /api/approvals/:approvalId/decision",
        ],
    },
    {
        "domain": "workflow-routing",
        "nodeModule": "apps/daemon/src/routes/workflow-routes.ts",
        "pythonStatus": "implemented",
        "routes": [
            "GET /api/skills",
            "GET /api/skills/file-management",
            "GET /api/skills/ui-contracts",
            "GET /api/skills/pages/:pageId",
            "GET /api/memory/sources",
            "POST /api/agent-route/preview",
        ],
    },
    {
        "domain": "jobsearch",
        "nodeModule": "apps/daemon/src/routes/search-routes.ts",
        "pythonStatus": "implemented",
        "routes": ["GET /api/search/jobsearch/sources", "POST /api/search/jobsearch"],
    },
    {
        "domain": "workspace-data",
        "nodeModule": "apps/daemon/src/routes/*-routes.ts",
        "pythonStatus": "partial-readonly",
        "routes": [
            "GET /api/workspace-file",
            "GET /api/profile-overview",
            "GET /api/resumes",
            "GET /api/resume",
            "GET /api/resumes/diagnostics",
            "POST /api/resumes/generate-preview",
            "POST /api/resumes/save-generated",
            "POST /api/resumes/save",
            "POST /api/resumes/export",
            "GET /api/resumes/export-file",
            "GET /api/applications",
            "POST /api/application-events",
            "POST /api/application-events/update",
            "POST /api/application-events/delete",
            "GET /api/reports",
            "GET /api/report",
            "GET /api/experience-overview",
            "POST /api/experience-metadata",
            "GET /api/recruitment-market",
            "POST /api/recruitment-market/import",
            "POST /api/recruitment-market/manual-jobs",
            "DELETE /api/recruitment-market/:id",
            "GET /api/evidence-requests",
            "POST /api/evidence-requests/fulfill",
            "POST /api/evidence-notes",
        ],
    },
]
