import { existsSync } from 'fs';
import { readFile, readdir, writeFile } from 'fs/promises';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { readJsonBody } from './request-utils.mjs';
import { readJsonFile, writeJsonFile } from '../data-store.mjs';
import { renderResumeDocx, renderResumePdf } from './render-service.mjs';
import { listRecruitmentMarket, sortMarketJobs } from './recruitment-service.mjs';

const root = resolve(fileURLToPath(new URL('../../', import.meta.url)));
const resumesDir = join(root, 'resumes');
const dataDir = join(root, 'data');
const resumeEditHistoryPath = join(dataDir, 'resume-edit-history.json');
const resumeVersionsPath = join(dataDir, 'resume-versions.json');
const experienceMetadataPath = join(dataDir, 'experience-metadata.json');

export function registerResumeRoutes(registerJsonRoute, registerRawRoute, options = {}) {
  const port = Number(options.port || 4173);
  registerJsonRoute('GET', '/api/resumes', listResumes);
  registerJsonRoute('POST', '/api/resumes/auto-generate', autoGenerateResume);
  registerRawRoute('GET', '/api/resume', (req, res, url) => sendResume(req, res, url));
  registerRawRoute('GET', '/api/resume-export', (req, res, url) => sendResumeExport(req, url, res, port));
  registerJsonRoute('GET', '/api/resume-edits', listResumeEdits);
  registerJsonRoute('POST', '/api/resume-line-edits', saveResumeLineEdits);
  registerJsonRoute('GET', '/api/resume-versions', listResumeVersions);
  registerJsonRoute('POST', '/api/resume-versions', createResumeVersion);
  registerJsonRoute('POST', '/api/resume-versions/restore', restoreResumeVersion);
}

async function listResumes() {
  const files = (await readdir(resumesDir))
    .filter((file) => /^\d{2}-.+\.md$/.test(file))
    .sort();
  return Promise.all(files.map(async (file) => {
    const text = await readFile(join(resumesDir, file), 'utf8');
    const title = text.match(/^#\s+(.+)$/m)?.[1] || file.replace(/\.md$/, '');
    return { file, title };
  }));
}

async function autoGenerateResume(req) {
  const body = await readJsonBody(req);
  let baseFile = '';
  try {
    baseFile = validateResumeFile(body.baseFile);
  } catch {
    baseFile = (await listResumes())[0]?.file || '';
  }
  if (!baseFile) throw new Error('No base resume found');

  const baseMarkdown = await readFile(join(resumesDir, baseFile), 'utf8');
  const title = autoResumeTitle(baseMarkdown);
  const experiences = await readJsonFile(experienceMetadataPath, { experiences: [] }).then((data) => data.experiences || []);
  const market = await listRecruitmentMarket();
  const topJobs = sortMarketJobs(market.jobs || [], 'score-desc').slice(0, 6);
  const content = buildAutoGeneratedResume({ title, baseMarkdown, experiences, topJobs });

  const existing = await listResumes();
  const used = new Set(existing.map((item) => Number(item.file.match(/^(\d{2})-/)?.[1] || 0)));
  const nextIndex = Array.from({ length: 10 }, (_, index) => 90 + index).find((index) => !used.has(index)) || 99;
  const file = `${String(nextIndex).padStart(2, '0')}-auto-generated-resume.md`;
  await writeFile(join(resumesDir, file), content, 'utf8');
  return { file, title: content.match(/^#\s+(.+)$/m)?.[1] || title };
}

function autoResumeTitle(baseMarkdown) {
  const baseTitle = baseMarkdown.match(/^#\s+(.+)$/m)?.[1] || '自动生成简历';
  const direction = baseTitle.split('-').pop()?.trim() || '目标岗位';
  return `韦东波 - ${direction}（自动生成）`;
}

function buildAutoGeneratedResume({ title, baseMarkdown, experiences, topJobs }) {
  const contact = baseMarkdown.match(/^#.+\n([\s\S]*?)(?=\n##\s+)/)?.[1]?.trim() || '';
  const targetRoles = topJobs.map((job) => job.role).filter(Boolean).slice(0, 4);
  const keywords = uniqueTerms(topJobs.flatMap((job) => [job.direction, ...(job.keywords || [])])).slice(0, 18);
  const selectedExperiences = (experiences || []).slice(0, 5);
  return `# ${title}
${contact ? `${contact}\n` : ''}
## 个人摘要

面向${targetRoles.length ? targetRoles.join('、') : '机器人系统、机器人软件和具身智能相关岗位'}生成的定制简历。重点突出项目经历中的机器人系统、工业通信、现场问题闭环、AI 工程化和数据基建能力，并对齐当前岗位机会雷达中的高频要求：${keywords.slice(0, 10).join('、')}。

## 核心技能

${chunkList(keywords.length ? keywords : ['机器人系统', 'EtherCAT', 'ROS2', 'CANopen', 'CiA402', 'SOEM', 'IGH EtherCAT', 'RAG', 'Agent', '数据闭环'], 4).map((group) => `- ${group.join('、')}`).join('\n')}

## 项目经历

${selectedExperiences.length ? selectedExperiences.map(renderAutoExperience).join('\n\n') : fallbackProjectSection(baseMarkdown)}

## 岗位匹配重点

${topJobs.length ? topJobs.map((job) => `- ${job.company} / ${job.role}：匹配 ${Number(job.matchScore || 0).toFixed(1)}，重点补强 ${job.evidenceGap || job.direction || '岗位证据'}。`).join('\n') : '- 暂无岗位机会数据，建议先在岗位机会雷达中完成检索。'}

## 待人工确认

- 请核对所有量化数据，避免写入未确认指标。
- 请根据目标岗位 JD 调整项目排序和关键词密度。
- 请补充客户反馈、故障率变化、控制周期、从站数量等可验证证据。`;
}

function renderAutoExperience(item) {
  const tags = [...(item.tags || []), ...(item.evidence || [])].slice(0, 8);
  const gaps = (item.gaps || []).slice(0, 3);
  return `### ${item.title}

- 方向：${item.category || item.role || '待确认方向'}
- 摘要：${item.summary || '待补充项目摘要。'}
- 关键词：${tags.join('、') || '待补充'}
${gaps.length ? `- 简历补强点：${gaps.join('、')}` : '- 简历补强点：补充量化结果、交付影响和可公开边界。'}`;
}

function fallbackProjectSection(baseMarkdown) {
  const section = baseMarkdown.match(/##\s+项目经历[\s\S]*?(?=\n##\s+|$)/)?.[0];
  return section
    ? section.replace(/^##\s+项目经历\s*/, '').trim()
    : '### 待补充项目经历\n\n- 请先在经历资产库导入项目经历文件。';
}

function chunkList(items, size) {
  const chunks = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

async function listResumeVersions(req, url) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = String(url.searchParams.get('file') || '');
  return readResumeVersionsForFile(file);
}

async function createResumeVersion(req) {
  const body = await readJsonBody(req);
  const file = validateResumeFile(body.file);
  const path = resolve(resumesDir, file);
  const content = await readFile(path, 'utf8');
  const now = new Date().toISOString();
  const title = content.match(/^#\s+(.+)$/m)?.[1] || file.replace(/\.md$/, '');
  const store = await readResumeVersions();
  const version = {
    id: `RV-${Date.now().toString(36)}`,
    file,
    title,
    note: String(body.note || '').trim(),
    content,
    createdAt: now,
    source: 'manual',
  };
  store.updatedAt = now;
  store.versions = [...(store.versions || []), version].slice(-500);
  await writeJsonFile(resumeVersionsPath, store);
  return { ok: true, version, ...(await readResumeVersionsForFile(file)) };
}

async function restoreResumeVersion(req) {
  const body = await readJsonBody(req);
  const file = validateResumeFile(body.file);
  const id = String(body.id || '');
  const store = await readResumeVersions();
  const version = (store.versions || []).find((item) => item.id === id && item.file === file);
  if (!version) throw new Error('Resume version not found');

  const path = resolve(resumesDir, file);
  await writeFile(path, String(version.content || ''), 'utf8');

  const now = new Date().toISOString();
  const restoreRecord = {
    id: `RV-${Date.now().toString(36)}-restore`,
    file,
    title: version.title,
    note: `恢复自 ${version.id}`,
    content: String(version.content || ''),
    createdAt: now,
    source: 'restore',
    restoredFrom: version.id,
  };
  store.updatedAt = now;
  store.versions = [...(store.versions || []), restoreRecord].slice(-500);
  await writeJsonFile(resumeVersionsPath, store);
  return { ok: true, restoredFrom: version.id, version: restoreRecord, ...(await readResumeVersionsForFile(file)) };
}

async function readResumeVersions() {
  return readJsonFile(resumeVersionsPath, { updatedAt: '', versions: [] });
}

async function readResumeVersionsForFile(file) {
  const store = await readResumeVersions();
  const versions = file
    ? (store.versions || []).filter((item) => item.file === file)
    : (store.versions || []);
  return {
    updatedAt: store.updatedAt || '',
    versions: versions.slice(-80).reverse().map((item) => ({
      id: item.id,
      file: item.file,
      title: item.title,
      note: item.note || '',
      createdAt: item.createdAt,
      source: item.source || 'manual',
      size: String(item.content || '').length,
    })),
  };
}

async function listResumeEdits(req, url) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = url.searchParams.get('file') || '';
  const history = await readResumeEditHistory();
  const edits = file ? history.edits.filter((item) => item.file === file) : history.edits;
  return {
    updatedAt: history.updatedAt || '',
    edits: edits.slice(-80).reverse(),
  };
}

async function saveResumeLineEdits(req) {
  const body = await readJsonBody(req);
  const file = String(body.file || '');
  if (!/^\d{2}-.+\.md$/.test(file)) throw new Error('Invalid resume file');
  const path = resolve(resumesDir, file);
  if (!path.startsWith(resumesDir) || !existsSync(path)) throw new Error('Resume not found');

  const changes = Array.isArray(body.changes) ? body.changes : [];
  const lines = (await readFile(path, 'utf8')).split(/\r?\n/);
  const now = new Date().toISOString();
  const records = [];

  for (const change of changes) {
    const lineIndex = Number(change.lineIndex);
    if (!Number.isInteger(lineIndex) || lineIndex < 0 || lineIndex >= lines.length) continue;
    const before = lines[lineIndex];
    const after = String(change.after ?? '');
    if (before === after) continue;
    lines[lineIndex] = after;
    records.push({
      id: `RE-${Date.now().toString(36)}-${records.length + 1}`,
      file,
      lineIndex,
      before,
      after,
      renderBefore: String(change.renderBefore || ''),
      renderAfter: String(change.renderAfter || ''),
      changedAt: now,
      source: 'rendered-preview',
    });
  }

  if (records.length) {
    await writeFile(path, lines.join('\n'), 'utf8');
    const history = await readResumeEditHistory();
    history.updatedAt = now;
    history.edits = [...(history.edits || []), ...records].slice(-500);
    await writeJsonFile(resumeEditHistoryPath, history);
  }

  return { ok: true, file, saved: records.length, records };
}

async function readResumeEditHistory() {
  return readJsonFile(resumeEditHistoryPath, { updatedAt: '', edits: [] });
}

function validateResumeFile(value) {
  const file = String(value || '');
  if (!/^\d{2}-.+\.md$/.test(file)) throw new Error('Invalid resume file');
  const path = resolve(resumesDir, file);
  if (!path.startsWith(resumesDir) || !existsSync(path)) throw new Error('Resume not found');
  return file;
}

async function sendResume(req, res, url) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = url.searchParams.get('file') || '';
  if (!/^\d{2}-.+\.md$/.test(file)) return notFound(res);
  const path = resolve(resumesDir, file);
  if (!path.startsWith(resumesDir) || !existsSync(path)) return notFound(res);
  const markdown = await readFile(path, 'utf8');
  sendJson(res, { file, markdown });
}

async function sendResumeExport(req, url, res, port) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = validateResumeFile(url.searchParams.get('file') || '');
  const format = String(url.searchParams.get('format') || 'pdf').toLowerCase();
  const markdown = await readFile(join(resumesDir, file), 'utf8');
  const title = markdown.match(/^#\s+(.+)$/m)?.[1] || file.replace(/\.md$/, '');
  const baseName = sanitizeFileName(title || file.replace(/\.md$/, ''));

  if (format === 'pdf') {
    const buffer = await renderResumePdf(file, port);
    return sendDownload(res, buffer, `${baseName}.pdf`, 'application/pdf');
  }

  if (format === 'docx') {
    const buffer = await renderResumeDocx(markdown, title);
    return sendDownload(res, buffer, `${baseName}.docx`, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  }

  return notFound(res);
}

function sendDownload(res, buffer, filename, contentType) {
  const asciiName = filename.replace(/[^\x20-\x7E]/g, '_');
  res.writeHead(200, {
    'content-type': contentType,
    'content-length': buffer.length,
    'content-disposition': `attachment; filename="${asciiName}"; filename*=UTF-8''${encodeURIComponent(filename)}`,
  });
  res.end(buffer);
}

function uniqueTerms(values) {
  const seen = new Set();
  return values.flatMap((value) => String(value || '').split(/[\s,，、/|]+/))
    .map((item) => item.trim())
    .filter((item) => item && item.length >= 2 && !/^(韦东波|招聘|职位|深圳)$/.test(item))
    .filter((item) => {
      if (seen.has(item)) return false;
      seen.add(item);
      return true;
    });
}

function sanitizeFileName(name) {
  return String(name).replace(/[\\/:*?"<>|]/g, '-').replace(/\s+/g, ' ').trim();
}

function sendJson(res, data) {
  res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(data));
}

function notFound(res) {
  res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' });
  res.end('Not found');
}
