import { existsSync } from 'fs';
import { spawn } from 'child_process';
import { readFile, readdir, writeFile } from 'fs/promises';
import { join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { readJsonBody } from './request-utils.mjs';
import { readJsonFile, writeJsonFile } from '../data-store.mjs';
import { renderResumeDocx, renderResumePdf } from './render-service.mjs';
import { listRecruitmentMarket, sortMarketJobs } from './recruitment-service.mjs';

const root = resolve(fileURLToPath(new URL('../../', import.meta.url)));
const resumesDir = join(root, 'resumes');
const dataDir = join(root, 'data');
const resumeEditHistoryPath = join(dataDir, 'resume-edit-history.json');
const resumeVersionsPath = join(dataDir, 'resume-versions.json');
const resumeJobLinksPath = join(dataDir, 'resume-job-links.json');
const experienceMetadataPath = join(dataDir, 'experience-metadata.json');
const codexBin = process.env.CODEX_BIN || 'codex';

export function registerResumeRoutes(registerJsonRoute, registerRawRoute, options = {}) {
  const port = Number(options.port || 4173);
  registerJsonRoute('GET', '/api/resumes', listResumes);
  registerJsonRoute('GET', '/api/resume-job-links', listResumeJobLinks);
  registerJsonRoute('POST', '/api/resumes/auto-generate', autoGenerateResume);
  registerRawRoute('GET', '/api/resume', (req, res, url) => sendResume(req, res, url));
  registerRawRoute('GET', '/api/resume-export', (req, res, url) => sendResumeExport(req, url, res, port));
  registerJsonRoute('GET', '/api/resume-edits', listResumeEdits);
  registerJsonRoute('POST', '/api/resume-line-edits', saveResumeLineEdits);
  registerJsonRoute('GET', '/api/resume-versions', listResumeVersions);
  registerJsonRoute('POST', '/api/resume-versions', createResumeVersion);
  registerJsonRoute('POST', '/api/resume-versions/restore', restoreResumeVersion);
}

async function listResumes() {
  const linkStore = await readResumeJobLinks();
  const linksByFile = new Map((linkStore.links || []).map((item) => [item.file, item]));
  const files = (await readdir(resumesDir))
    .filter((file) => /^\d{2}-.+\.md$/.test(file))
    .sort();
  return Promise.all(files.map(async (file) => {
    const text = await readFile(join(resumesDir, file), 'utf8');
    const title = text.match(/^#\s+(.+)$/m)?.[1] || file.replace(/\.md$/, '');
    const link = linksByFile.get(file);
    return {
      file,
      title,
      targetJobId: link?.jobId || '',
      targetJobTitle: link?.jobTitle || '',
      generatedAt: link?.generatedAt || '',
    };
  }));
}

async function listResumeJobLinks() {
  const store = await readResumeJobLinks();
  return {
    updatedAt: store.updatedAt || '',
    links: (store.links || []).filter((item) => {
      return item?.file && existsSync(join(resumesDir, item.file));
    }),
  };
}

async function autoGenerateResume(req) {
  const body = await readJsonBody(req);
  let baseFile = '';
  try {
    baseFile = validateResumeFile(body.baseFile);
  } catch {
    baseFile = (await listResumes())[0]?.file || '';
  }
  if (!baseFile) throw new Error('No base resume found');

  const baseMarkdown = await readFile(join(resumesDir, baseFile), 'utf8');
  const market = await listRecruitmentMarket();
  const targetJob = await selectTargetJob(market.jobs || [], body.targetJobId, baseMarkdown);
  const title = autoResumeTitle(baseMarkdown, targetJob);
  const experiences = await readJsonFile(experienceMetadataPath, { experiences: [] }).then((data) => data.experiences || []);
  const topJobs = targetJob
    ? [targetJob, ...(await sortedMarketJobs((market.jobs || []).filter((job) => job.id !== targetJob.id))).slice(0, 5)]
    : (await sortedMarketJobs(market.jobs || [])).slice(0, 6);
  const rankedExperiences = rankExperiencesForJob(experiences, targetJob || topJobs[0]);
  const deterministicContent = buildAutoGeneratedResume({
    title,
    baseMarkdown,
    experiences: rankedExperiences,
    topJobs,
    targetJob,
  });
  const llmContent = await generateResumeWithCodex({
    title,
    baseMarkdown,
    experiences: rankedExperiences,
    targetJob,
    topJobs,
    fallbackContent: deterministicContent,
  });
  const content = llmContent || deterministicContent;

  const existing = await listResumes();
  const used = new Set(existing.map((item) => Number(item.file.match(/^(\d{2})-/)?.[1] || 0)));
  const nextIndex = Array.from({ length: 10 }, (_, index) => 90 + index).find((index) => !used.has(index)) || 99;
  const file = `${String(nextIndex).padStart(2, '0')}-auto-generated-resume.md`;
  await writeFile(join(resumesDir, file), content, 'utf8');
  const generatedTitle = content.match(/^#\s+(.+)$/m)?.[1] || title;
  if (targetJob?.id) {
    await upsertResumeJobLink({
      file,
      title: generatedTitle,
      baseFile,
      targetJob,
      engine: llmContent ? 'codex-llm' : 'local-fallback',
      sourceSnapshotHash: sourceSnapshotHash({ baseMarkdown, targetJob, experiences: rankedExperiences }),
    });
  }
  return {
    file,
    title: generatedTitle,
    targetJob: targetJob ? compactJob(targetJob) : null,
    engine: llmContent ? 'codex-llm' : 'local-fallback',
  };
}

async function readResumeJobLinks() {
  return readJsonFile(resumeJobLinksPath, { updatedAt: '', links: [] });
}

async function upsertResumeJobLink({ file, title, baseFile, targetJob, engine, sourceSnapshotHash }) {
  const store = await readResumeJobLinks();
  const now = new Date().toISOString();
  const jobTitle = [targetJob.company, targetJob.role].filter(Boolean).join(' - ');
  const link = {
    jobId: targetJob.id,
    jobTitle,
    company: targetJob.company || '',
    role: targetJob.role || '',
    file,
    title,
    baseFile,
    generatedAt: now,
    engine,
    sourceSnapshotHash,
  };
  store.updatedAt = now;
  store.links = [
    ...(store.links || []).filter((item) => item.jobId !== targetJob.id && item.file !== file),
    link,
  ].slice(-500);
  await writeJsonFile(resumeJobLinksPath, store);
  return link;
}

function sourceSnapshotHash(payload) {
  const text = JSON.stringify({
    base: String(payload.baseMarkdown || '').slice(0, 12000),
    job: compactJob(payload.targetJob || {}),
    experiences: (payload.experiences || []).slice(0, 8).map((item) => ({
      title: item.title,
      summary: item.summary,
      tags: item.tags,
      evidence: item.evidence,
    })),
  });
  let hash = 2166136261;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16);
}

function autoResumeTitle(baseMarkdown, targetJob = null) {
  const baseTitle = baseMarkdown.match(/^#\s+(.+)$/m)?.[1] || '自动生成简历';
  const direction = targetJob?.role || baseTitle.split('-').pop()?.trim() || '目标岗位';
  return `韦东波 - ${direction}`;
}

function buildAutoGeneratedResume({ title, baseMarkdown, experiences, topJobs, targetJob = null }) {
  const contact = baseMarkdown.match(/^#.+\n([\s\S]*?)(?=\n##\s+)/)?.[1]?.trim() || '';
  const targetRoles = topJobs.map((job) => job.role).filter(Boolean).slice(0, 4);
  const keywords = jobKeywords(targetJob || topJobs[0] || {}).length
    ? jobKeywords(targetJob || topJobs[0] || {}).slice(0, 18)
    : uniqueTerms(topJobs.flatMap((job) => [job.direction, ...(job.keywords || [])])).slice(0, 18);
  const selectedExperiences = (experiences || []).slice(0, 5);
  return `# ${title}
${contact ? `${contact}\n` : ''}
## 个人摘要

面向${targetJob ? `${targetJob.company || '目标公司'}的${targetJob.role || '目标岗位'}` : targetRoles.length ? targetRoles.join('、') : '机器人系统、机器人软件和具身智能相关岗位'}生成的定制简历。重点突出项目经历中的机器人系统、工业通信、现场问题闭环、AI 工程化和数据基建能力，并对齐岗位信号：${keywords.slice(0, 10).join('、')}。

## 核心技能

${chunkList(keywords.length ? keywords : ['机器人系统', 'EtherCAT', 'ROS2', 'CANopen', 'CiA402', 'SOEM', 'IGH EtherCAT', 'RAG', 'Agent', '数据闭环'], 4).map((group) => `- ${group.join('、')}`).join('\n')}

## 项目经历

${selectedExperiences.length ? selectedExperiences.map(renderAutoExperience).join('\n\n') : fallbackProjectSection(baseMarkdown)}

## 岗位匹配重点

${targetJob ? `- 目标岗位：${targetJob.company || '待确认公司'} / ${targetJob.role || '待确认岗位'}；来源：${targetJob.source || '手工导入'}；地点：${targetJob.location || '待确认'}。
- JD 信号：${keywords.slice(0, 14).join('、') || '待补充'}。
- 证据缺口：${targetJob.evidenceGap || '请继续补充岗位要求中尚未覆盖的项目证据。'}` : topJobs.length ? topJobs.map((job) => `- ${job.company} / ${job.role}：匹配 ${Number(job.matchScore || 0).toFixed(1)}，重点补强 ${job.evidenceGap || job.direction || '岗位证据'}。`).join('\n') : '- 暂无岗位机会数据，建议先在岗位机会雷达中完成检索。'}

## 待人工确认

- 请核对所有量化数据，避免写入未确认指标。
- 请根据目标岗位 JD 调整项目排序和关键词密度。
- 请补充客户反馈、故障率变化、控制周期、从站数量等可验证证据。`;
}

async function generateResumeWithCodex({ title, baseMarkdown, experiences, targetJob, topJobs, fallbackContent }) {
  if (process.env.RESUME_LLM_DISABLED === '1') return '';
  if (codexBin.includes('/') && !existsSync(codexBin)) return '';
  const prompt = await buildResumeCodexPrompt({ title, baseMarkdown, experiences, targetJob, topJobs, fallbackContent });
  try {
    const { stdout } = await runCodexExec(prompt, { timeoutMs: 240_000 });
    return normalizeGeneratedMarkdown(stdout);
  } catch {
    return '';
  }
}

async function buildResumeCodexPrompt({ title, baseMarkdown, experiences, targetJob, topJobs, fallbackContent }) {
  const sourceExperiences = await Promise.all((experiences || []).slice(0, 6).map(async (item) => ({
    ...item,
    sourceContent: await readSafeRelativeFile(item.sourceFile, 4000),
  })));
  return `你是一个严谨的中文求职简历优化助手。请根据“目标岗位 JD 信号、候选人的经历资产库、当前简历”生成一份 ATS 友好的中文 Markdown 简历。

硬性规则：
1. 只能使用输入中已经存在的经历、技能、项目、指标和事实，禁止编造公司、项目、指标、奖项、论文、专利、客户结果。
2. 可以重写表达、重排项目、合并重复技能，但不能把“规划/demo/待补充”的内容写成已完成生产成果。
3. 如果证据不足，在最后的“待人工确认”里列出，不要伪造成果。
4. 输出必须是 Markdown，只输出简历正文，不要解释，不要代码块。
5. 必须包含这些二级标题：个人摘要、核心技能、项目经历、工作经历、教育背景、待人工确认。
6. 第一行标题必须是：# ${title}

目标岗位：
${JSON.stringify(compactJob(targetJob || topJobs?.[0] || {}), null, 2)}

相关岗位补充信号：
${JSON.stringify((topJobs || []).slice(0, 4).map(compactJob), null, 2)}

经历资产库：
${JSON.stringify(sourceExperiences, null, 2)}

当前基础简历：
${baseMarkdown.slice(0, 12000)}

本地规则生成草稿，可作为结构参考：
${fallbackContent.slice(0, 8000)}
`;
}

function runCodexExec(prompt, { timeoutMs = 180_000 } = {}) {
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(codexBin, ['exec', '--ephemeral', '--dangerously-bypass-approvals-and-sandbox', prompt], {
      cwd: root,
      env: {
        ...process.env,
        NO_COLOR: '1',
      },
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stdout = '';
    let stderr = '';
    const timer = setTimeout(() => {
      child.kill('SIGTERM');
      const err = new Error('codex exec timed out');
      err.stdout = stdout;
      err.stderr = stderr;
      rejectPromise(err);
    }, timeoutMs);
    child.stdout.on('data', (chunk) => { stdout += chunk.toString(); });
    child.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    child.on('error', (err) => {
      clearTimeout(timer);
      err.stdout = stdout;
      err.stderr = stderr;
      rejectPromise(err);
    });
    child.on('close', (code, signal) => {
      clearTimeout(timer);
      if (code === 0) return resolvePromise({ stdout, stderr });
      const err = new Error(`codex exec exited with ${signal || code}`);
      err.stdout = stdout;
      err.stderr = stderr;
      rejectPromise(err);
    });
  });
}

async function readSafeRelativeFile(relativePath, maxLength = 4000) {
  if (!relativePath) return '';
  const path = resolve(root, String(relativePath));
  if (!path.startsWith(root) || !existsSync(path)) return '';
  try {
    return (await readFile(path, 'utf8')).slice(0, maxLength);
  } catch {
    return '';
  }
}

function normalizeGeneratedMarkdown(output) {
  const text = String(output || '')
    .replace(/^```(?:markdown)?\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();
  const start = text.search(/^#\s+/m);
  const markdown = start >= 0 ? text.slice(start).trim() : text;
  if (!markdown.startsWith('# ')) return '';
  if (!/##\s+项目经历/.test(markdown) || !/##\s+待人工确认/.test(markdown)) return '';
  if (markdown.length < 800) return '';
  return markdown.endsWith('\n') ? markdown : `${markdown}\n`;
}

async function selectTargetJob(jobs, targetJobId, baseMarkdown) {
  const validJobs = (jobs || []).filter((job) => job && job.role && !isPlaceholderJob(job));
  const id = String(targetJobId || '').trim();
  if (id) return validJobs.find((job) => job.id === id) || null;
  const title = baseMarkdown.match(/^#\s+(.+)$/m)?.[1] || '';
  const titleTerms = uniqueTerms([title]).map((item) => item.toLowerCase());
  const sortedJobs = await sortedMarketJobs(validJobs);
  return sortedJobs.find((job) => {
    const text = [job.company, job.role, job.direction, ...(job.keywords || [])].join(' ').toLowerCase();
    return titleTerms.some((term) => text.includes(term));
  }) || sortedJobs[0] || null;
}

async function sortedMarketJobs(jobs) {
  return sortMarketJobs(jobs || [], 'score-desc');
}

function isPlaceholderJob(job) {
  return /待解析|待复核公司|待复核岗位/.test(`${job.company || ''}${job.role || ''}`);
}

function rankExperiencesForJob(experiences, job) {
  const terms = jobKeywords(job);
  return [...(experiences || [])].map((item, index) => ({
    item,
    index,
    score: experienceMatchScore(item, terms),
  })).sort((a, b) => b.score - a.score || a.index - b.index).map((entry) => entry.item);
}

function experienceMatchScore(item, terms) {
  const text = [
    item.title,
    item.category,
    item.role,
    item.summary,
    ...(item.tags || []),
    ...(item.evidence || []),
    ...(item.gaps || []),
  ].join(' ').toLowerCase();
  return terms.reduce((score, term) => score + (text.includes(term.toLowerCase()) ? 1 : 0), 0);
}

function jobKeywords(job = {}) {
  return uniqueTerms([
    job.company,
    job.role,
    job.direction,
    job.salary,
    job.fitReason,
    job.evidenceGap,
    job.rawText,
    ...(job.keywords || []),
  ]).slice(0, 24);
}

function compactJob(job = {}) {
  return {
    id: job.id || '',
    company: job.company || '',
    role: job.role || '',
    direction: job.direction || '',
    location: job.location || '',
    salary: job.salary || '',
    source: job.source || '',
    url: job.url || '',
    matchScore: job.matchScore || '',
    keywords: (job.keywords || []).slice(0, 16),
    fitReason: job.fitReason || '',
    evidenceGap: job.evidenceGap || '',
    rawText: String(job.rawText || '').slice(0, 2400),
  };
}

function renderAutoExperience(item) {
  const tags = [...(item.tags || []), ...(item.evidence || [])].slice(0, 8);
  const gaps = (item.gaps || []).slice(0, 3);
  return `### ${item.title}

- 方向：${item.category || item.role || '待确认方向'}
- 摘要：${item.summary || '待补充项目摘要。'}
- 关键词：${tags.join('、') || '待补充'}
${gaps.length ? `- 简历补强点：${gaps.join('、')}` : '- 简历补强点：补充量化结果、交付影响和可公开边界。'}`;
}

function fallbackProjectSection(baseMarkdown) {
  const section = baseMarkdown.match(/##\s+项目经历[\s\S]*?(?=\n##\s+|$)/)?.[0];
  return section
    ? section.replace(/^##\s+项目经历\s*/, '').trim()
    : '### 待补充项目经历\n\n- 请先在经历资产库导入项目经历文件。';
}

function chunkList(items, size) {
  const chunks = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

async function listResumeVersions(req, url) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = String(url.searchParams.get('file') || '');
  return readResumeVersionsForFile(file);
}

async function createResumeVersion(req) {
  const body = await readJsonBody(req);
  const file = validateResumeFile(body.file);
  const path = resolve(resumesDir, file);
  const content = await readFile(path, 'utf8');
  const now = new Date().toISOString();
  const title = content.match(/^#\s+(.+)$/m)?.[1] || file.replace(/\.md$/, '');
  const store = await readResumeVersions();
  const version = {
    id: `RV-${Date.now().toString(36)}`,
    file,
    title,
    note: String(body.note || '').trim(),
    content,
    createdAt: now,
    source: 'manual',
  };
  store.updatedAt = now;
  store.versions = [...(store.versions || []), version].slice(-500);
  await writeJsonFile(resumeVersionsPath, store);
  return { ok: true, version, ...(await readResumeVersionsForFile(file)) };
}

async function restoreResumeVersion(req) {
  const body = await readJsonBody(req);
  const file = validateResumeFile(body.file);
  const id = String(body.id || '');
  const store = await readResumeVersions();
  const version = (store.versions || []).find((item) => item.id === id && item.file === file);
  if (!version) throw new Error('Resume version not found');

  const path = resolve(resumesDir, file);
  await writeFile(path, String(version.content || ''), 'utf8');

  const now = new Date().toISOString();
  const restoreRecord = {
    id: `RV-${Date.now().toString(36)}-restore`,
    file,
    title: version.title,
    note: `恢复自 ${version.id}`,
    content: String(version.content || ''),
    createdAt: now,
    source: 'restore',
    restoredFrom: version.id,
  };
  store.updatedAt = now;
  store.versions = [...(store.versions || []), restoreRecord].slice(-500);
  await writeJsonFile(resumeVersionsPath, store);
  return { ok: true, restoredFrom: version.id, version: restoreRecord, ...(await readResumeVersionsForFile(file)) };
}

async function readResumeVersions() {
  return readJsonFile(resumeVersionsPath, { updatedAt: '', versions: [] });
}

async function readResumeVersionsForFile(file) {
  const store = await readResumeVersions();
  const versions = file
    ? (store.versions || []).filter((item) => item.file === file)
    : (store.versions || []);
  return {
    updatedAt: store.updatedAt || '',
    versions: versions.slice(-80).reverse().map((item) => ({
      id: item.id,
      file: item.file,
      title: item.title,
      note: item.note || '',
      createdAt: item.createdAt,
      source: item.source || 'manual',
      size: String(item.content || '').length,
    })),
  };
}

async function listResumeEdits(req, url) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = url.searchParams.get('file') || '';
  const history = await readResumeEditHistory();
  const edits = file ? history.edits.filter((item) => item.file === file) : history.edits;
  return {
    updatedAt: history.updatedAt || '',
    edits: edits.slice(-80).reverse(),
  };
}

async function saveResumeLineEdits(req) {
  const body = await readJsonBody(req);
  const file = String(body.file || '');
  if (!/^\d{2}-.+\.md$/.test(file)) throw new Error('Invalid resume file');
  const path = resolve(resumesDir, file);
  if (!path.startsWith(resumesDir) || !existsSync(path)) throw new Error('Resume not found');

  const changes = Array.isArray(body.changes) ? body.changes : [];
  const lines = (await readFile(path, 'utf8')).split(/\r?\n/);
  const now = new Date().toISOString();
  const records = [];

  for (const change of changes) {
    const lineIndex = Number(change.lineIndex);
    if (!Number.isInteger(lineIndex) || lineIndex < 0 || lineIndex >= lines.length) continue;
    const before = lines[lineIndex];
    const after = String(change.after ?? '');
    if (before === after) continue;
    lines[lineIndex] = after;
    records.push({
      id: `RE-${Date.now().toString(36)}-${records.length + 1}`,
      file,
      lineIndex,
      before,
      after,
      renderBefore: String(change.renderBefore || ''),
      renderAfter: String(change.renderAfter || ''),
      changedAt: now,
      source: 'rendered-preview',
    });
  }

  if (records.length) {
    await writeFile(path, lines.join('\n'), 'utf8');
    const history = await readResumeEditHistory();
    history.updatedAt = now;
    history.edits = [...(history.edits || []), ...records].slice(-500);
    await writeJsonFile(resumeEditHistoryPath, history);
  }

  return { ok: true, file, saved: records.length, records };
}

async function readResumeEditHistory() {
  return readJsonFile(resumeEditHistoryPath, { updatedAt: '', edits: [] });
}

function validateResumeFile(value) {
  const file = String(value || '');
  if (!/^\d{2}-.+\.md$/.test(file)) throw new Error('Invalid resume file');
  const path = resolve(resumesDir, file);
  if (!path.startsWith(resumesDir) || !existsSync(path)) throw new Error('Resume not found');
  return file;
}

async function sendResume(req, res, url) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = url.searchParams.get('file') || '';
  if (!/^\d{2}-.+\.md$/.test(file)) return notFound(res);
  const path = resolve(resumesDir, file);
  if (!path.startsWith(resumesDir) || !existsSync(path)) return notFound(res);
  const markdown = await readFile(path, 'utf8');
  sendJson(res, { file, markdown });
}

async function sendResumeExport(req, url, res, port) {
  if (!url && req && req.url) url = new URL(req.url, 'http://localhost');
  const file = validateResumeFile(url.searchParams.get('file') || '');
  const format = String(url.searchParams.get('format') || 'pdf').toLowerCase();
  const markdown = await readFile(join(resumesDir, file), 'utf8');
  const title = markdown.match(/^#\s+(.+)$/m)?.[1] || file.replace(/\.md$/, '');
  const baseName = sanitizeFileName(title || file.replace(/\.md$/, ''));

  if (format === 'pdf') {
    const buffer = await renderResumePdf(file, port);
    return sendDownload(res, buffer, `${baseName}.pdf`, 'application/pdf');
  }

  if (format === 'docx') {
    const buffer = await renderResumeDocx(markdown, title);
    return sendDownload(res, buffer, `${baseName}.docx`, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  }

  return notFound(res);
}

function sendDownload(res, buffer, filename, contentType) {
  const asciiName = filename.replace(/[^\x20-\x7E]/g, '_');
  res.writeHead(200, {
    'content-type': contentType,
    'content-length': buffer.length,
    'content-disposition': `attachment; filename="${asciiName}"; filename*=UTF-8''${encodeURIComponent(filename)}`,
  });
  res.end(buffer);
}

function uniqueTerms(values) {
  const seen = new Set();
  return values.flatMap((value) => String(value || '').split(/[\s,，、/|]+/))
    .map((item) => item.trim())
    .filter((item) => item && item.length >= 2 && !/^(韦东波|招聘|职位|深圳)$/.test(item))
    .filter((item) => {
      if (seen.has(item)) return false;
      seen.add(item);
      return true;
    });
}

function sanitizeFileName(name) {
  return String(name).replace(/[\\/:*?"<>|]/g, '-').replace(/\s+/g, ' ').trim();
}

function sendJson(res, data) {
  res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(data));
}

function notFound(res) {
  res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' });
  res.end('Not found');
}
